version: '3.4'

services:
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 63790:6379
    volumes:
      - redis_data-1:/bitnami/redis/data-1

volumes:
  postgresql_master_data-1:
  redis_data-1:
    driver: local
