# Generated by Django 4.2.2 on 2023-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('tier_id', models.IntegerField(choices=[(1, 'tier-1'), (2, 'tier-2'), (3, 'tier-3')], default=1)),
                ('plan_code', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('insured_pattern', models.IntegerField()),
                ('sum_insured', models.IntegerField()),
                ('tenure', models.IntegerField(choices=[(1, '1 Year'), (2, '2 Year'), (3, '3 Year')], default=1)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
